swagger: "2.0"
info:
  description: This is the swagger file for the micro-IMDB project
  version: "0.1.0"
  title: uIMDB Movie Database
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the application
paths:
  /movie:
    get:
      operationId: movie.read_all
      summary: Read the entire set of movies
      description: Read the entire set of movies
      responses:
        200:
          description: Successfully read movie set operation
          schema:
            type: array
            items:
              properties:
                movie_id:
                  type: string
                  description: Id of the movie
                movie_name:
                  type: string
                  description: The movie name
                genre:
                  type: string
                  description: The movie genre
                studio:
                  type: string
                  description: The Studio, that created the movie
                audience:
                  type: integer
                  description: Audience
                profitability:
                  type: number
                  description: The profitability of this movie
                rotten_tomatoes_score:
                  type: integer
                  description: The Rotten Tomatoes score in %
                worldwide_gross:
                  type: string
                  description: Worldwide Gross
                year:
                  type: integer
                  description: Movie year
                timestamp:
                  type: string
                  description: Creation/Update timestamp of the movie record

    post:
      operationId: movie.create
      summary: Create a new movie record
      description: Create a new movie record
      parameters:
        - name: movie
          in: body
          description: Movie record to create
          required: True
          schema:
            type: object
            properties:
                movie_name:
                  type: string
                  description: The movie name
                genre:
                  type: string
                  description: The movie genre
                studio:
                  type: string
                  description: The Studio, that created the movie
                audience:
                  type: integer
                  description: Audience
                profitability:
                  type: number
                  description: The profitability of this movie
                rotten_tomatoes_score:
                  type: integer
                  description: The Rotten Tomatoes score in %
                worldwide_gross:
                  type: string
                  description: Worldwide Gross
                year:
                  type: integer
                  description: Movie year
      responses:
        201:
          description: Successfully created movie record
          schema:
            properties:
                movie_id:
                  type: string
                  description: Id of the movie
                movie_name:
                  type: string
                  description: The movie name
                genre:
                  type: string
                  description: The movie genre
                studio:
                  type: string
                  description: The Studio, that created the movie
                audience:
                  type: integer
                  description: Audience
                profitability:
                  type: number
                  description: The profitability of this movie
                rotten_tomatoes_score:
                  type: integer
                  description: The Rotten Tomatoes score in %
                worldwide_gross:
                  type: string
                  description: Worldwide Gross
                year:
                  type: integer
                  description: Movie year
                timestamp:
                  type: string
                  description: Creation/Update timestamp of the movie record

  /movie/{movie_id}:
    get:
      operationId: movie.read_one
      summary: Read one movie record
      description: Read one movie record
      parameters:
        - name: movie_id
          in: path
          description: Id of the movie to get
          type: integer
          required: True
        - name: fields
          in: query
          description: Id of the movie to get
          type: string
          required: False
      responses:
        200:
          description: Successfully read movie from the movies DB
          schema:
            type: object
            properties:
                movie_id:
                  type: string
                  description: Id of the movie
                movie_name:
                  type: string
                  description: The movie name
                genre:
                  type: string
                  description: The movie genre
                studio:
                  type: string
                  description: The Studio, that created the movie
                audience:
                  type: integer
                  description: Audience
                profitability:
                  type: number
                  description: The profitability of this movie
                rotten_tomatoes_score:
                  type: integer
                  description: The Rotten Tomatoes score in %
                worldwide_gross:
                  type: string
                  description: Worldwide Gross
                year:
                  type: integer
                  description: Movie year
                timestamp:
                  type: string
                  description: Creation/Update timestamp of the movie record